In [ ]:
num = int(input("Enter a number: "))  
factorial = 1  
if num < 0:  
   print("Sorry, factorial does not exist for negative numbers")  
elif (num == 0):
   print("The factorial of 0 is 1") 
else:  
   for i in range(1,num + 1):  
       factorial = factorial*i  
   print("The factorial of",num,"is",factorial) 

Enter a number: 7
The factorial of 7 is 5040


In [ ]:
def factorial(n): 
      
    # single line to find factorial 
    return 1 if (n==1 or n==0) else n * factorial(n - 1);  
  
# Driver Code 
num = 5; 
print("Factorial of",num,"is", 
factorial(num))

Factorial of 5 is 120


In [ ]:
num = int(input("Enter a number: "))  
prev=0 
curr =1
for i in range(0,num):
  print(prev)
  new = prev+curr
  prev=curr
  curr=new
  i=i+1
     

Enter a number: 5
0
1
1
2
3


In [ ]:
def Fibonacci(n): 
    if n<0: 
        print("Incorrect input") 
    # First Fibonacci number is 0 
    elif n==1: 
        return 0
    # Second Fibonacci number is 1 
    elif n==2: 
        return 1
    else: 
        return Fibonacci(n-1)+Fibonacci(n-2) 
  
# Driver Program 
  
print(Fibonacci(9)) 

21


In [ ]:
def compound_interest(principle, rate, time): 
  
    # Calculates compound interest  
    Amount = principle * (pow((1 + rate / 100), time)) 
    CI = Amount - principle 
    print("Compound interest is", CI) 
  
# Driver Code  
compound_interest(10000, 10.25, 5)

Compound interest is 6288.946267774416


In [ ]:
import math 
  
# A utility function that returns true if x is perfect square 
def isPerfectSquare(x): 
    s = int(math.sqrt(x)) 
    return s*s == x 
  
# Returns true if n is a Fibinacci Number, else false 
def isFibonacci(n): 
  
    # n is Fibinacci if one of 5*n*n + 4 or 5*n*n - 4 or both 
    # is a perferct square 
    return isPerfectSquare(5*n*n + 4) or isPerfectSquare(5*n*n - 4) 
     
# A utility function to test above functions 
for i in range(1,11): 
     if (isFibonacci(i) == True): 
         print  (i," is a Fibonacci Number")
     else: 
         print (i," is a not Fibonacci Number ")

1  is a Fibonacci Number
2  is a Fibonacci Number
3  is a Fibonacci Number
4  is a not Fibonacci Number 
5  is a Fibonacci Number
6  is a not Fibonacci Number 
7  is a not Fibonacci Number 
8  is a Fibonacci Number
9  is a not Fibonacci Number 
10  is a not Fibonacci Number 


In [ ]:
def squaresum(n) : 
  
    # Iterate i from 1  
    # and n finding  
    # square of i and 
    # add to sum. 
    sm = 0
    for i in range(1, n+1) : 
        sm = sm + (i * i) 
      
    return sm 
  
# Driven Program 
n = 4
print(squaresum(n)) 

30


In [ ]:
def sumOfSeries(n): 
    sum = 0
    for i in range(1, n+1): 
        sum +=i*i*i 
          
    return sum
  
   
# Driver Function 
n = 5
print(sumOfSeries(n)) 

225


In [ ]:
def largest(arr,n): 
  
    # Initialize maximum element 
    max = arr[0] 
  
    # Traverse array elements from second 
    # and compare every element with  
    # current max 
    for i in range(1, n): 
        if arr[i] > max: 
            max = arr[i] 
    return max
  
# Driver Code 
arr = [10, 324, 45, 90, 9808] 
n = len(arr) 
Ans = largest(arr,n) 
print ("Largest in given array is",Ans) 

Largest in given array is 9808


In [ ]:
# Find remainder of arr[0] * arr[1] 
# * .. * arr[n-1] 
def findremainder(arr, lens, n): 
    mul = 1
  
    # find the individual 
    # remainder and  
    # multiple with mul. 
    for i in range(lens):  
        mul = (mul * (arr[i] % n)) % n 
      
    return mul % n 
  
# Driven code 
arr = [ 100, 10, 5, 25, 35, 14 ] 
lens = len(arr) 
n = 11
  
# print the remainder 
# of after multiple 
# all the numbers 
print( findremainder(arr, lens, n))

9


In [ ]:
# Swap function
def swapList(newList):
    size = len(newList)
     
    # Swapping 
    temp = newList[0]
    newList[0] = newList[size - 1]
    newList[size - 1] = temp
     
    return newList
     
# Driver code
newList = [12, 35, 9, 56, 24]
 
print(swapList(newList))

[24, 35, 9, 56, 12]


In [ ]:
# Python program to find sum of elements in list
total = 0
 
# creating a list
list1 = [11, 5, 17, 18, 23] 
 
# Iterate each element in list
# and add them in variale total
for ele in range(0, len(list1)):
    total = total + list1[ele]
 
# printing total value
print("Sum of all elements in given list: ", total)

Sum of all elements in given list:  74


In [ ]:
# Function returns N largest elements 
def Nmaxelements(list1, N): 
    final_list = [] 
  
    for i in range(0, N):  
        max1 = 0
          
        for j in range(len(list1)):      
            if list1[j] > max1: 
                max1 = list1[j]; 
                  
        list1.remove(max1); 
        final_list.append(max1) 
          
    print(final_list) 
  
# Driver code 
list1 = [2, 6, 41, 85, 0, 3, 7, 6, 10] 
N = 2
  
# Calling the function 
Nmaxelements(list1, N)

[85, 41]


In [ ]:
# creating a list 
list1 = [11, 5, 17, 18, 23, 50]  
  
# Iterate each element in list 
# and add them in variale total 
for ele in list1: 
    if ele % 2 == 0: 
        list1.remove(ele) 
  
# printing modified list 
print("New list after removing all even numbers: ", list1) 

New list after removing all even numbers:  [11, 5, 17, 23]


In [1]:
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [2]:
# importing numpy as np 
import numpy as np 
  
  
# creating first matrix 
A = np.array([[1, 2], [3, 4]]) 
  
# creating second matrix 
B = np.array([[4, 5], [6, 7]]) 
  
print("Printing elements of first matrix") 
print(A) 
print("Printing elements of second matrix") 
print(B) 
  
# adding two matrix 
print("Addition of two matrix") 
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [3]:
# creating first matrix 
A = np.array([[1, 2], [3, 4]]) 
  
# creating second matrix 
B = np.array([[4, 5], [6, 7]]) 
  
print("Printing elements of first matrix") 
print(A) 
print("Printing elements of second matrix") 
print(B) 
  
# subtracting two matrix 
print("Subtraction of two matrix") 
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [5]:
# initializing N 
N = 4
  
# printing dimension 
print("The dimension : " + str(N)) 
  
# using list comprehension 
# matrix creation of n * n 
res = [list(range(1 + N * i, 1 + N * (i + 1))) 
                            for i in range(N)] 
  
# print result 
print("The created matrix of N * N: " + str(res)) 

The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [6]:
# function which return reverse of a string
 
def isPalindrome(s):
    return s == s[::-1]
 
 
# Driver code
s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

Yes


In [7]:
# Function to reverse words of string  
  
def rev_sentence(sentence):  
  
    # first split the string into words  
    words = sentence.split(' ')  
  
    # then reverse the split string list and join using space  
    reverse_sentence = ' '.join(reversed(words))  
  
    # finally return the joined string  
    return reverse_sentence  
  
if __name__ == "__main__":  
    input = 'hello World! 123 ++++'
    print (rev_sentence(input)) 

++++ 123 World! hello


In [10]:
def split_string(string): 
  
    # Split the string based on space delimiter 
    list_string = string.split(' ') 
      
    return list_string 
  
def join_string(list_string): 
  
    # Join the string based on '-' delimiter 
    string = '-'.join(list_string) 
      
    return string 
  
# Driver Function 
if __name__ == '__main__': 
    string = 'WORLD! HELLO 123+321'
      
    # Splitting a string 
    list_string = split_string(string) 
    print(list_string) 
  
     # Join list of strings into one 
    new_string = join_string(list_string) 
    print(new_string)

['WORLD!', 'HELLO', '123+321']
WORLD!-HELLO-123+321


In [12]:
# Python 3 program for recursive binary search.
# Modifications needed for the older Python 2 are found in comments.
 
# Returns index of x in arr if present, else -1
def binary_search(arr, low, high, x):
 
    # Check base case
    if high >= low:
 
        mid = (high + low) // 2
 
        # If element is present at the middle itself
        if arr[mid] == x:
            return mid
 
        # If element is smaller than mid, then it can only
        # be present in left subarray
        elif arr[mid] > x:
            return binary_search(arr, low, mid - 1, x)
 
        # Else the element can only be present in right subarray
        else:
            return binary_search(arr, mid + 1, high, x)
 
    else:
        # Element is not present in the array
        return -1
 
# Test array
arr = [ 2, 3, 4, 10, 40 ]
x = 10
 
# Function call
result = binary_search(arr, 0, len(arr)-1, x)
 
if result != -1:
    print("Element is present at index", str(result))
else:
    print("Element is not present in array")

Element is present at index 3


In [13]:
def binary_search(arr, x):
    low = 0
    high = len(arr) - 1
    mid = 0
 
    while low <= high:
 
        mid = (high + low) // 2
 
        # If x is greater, ignore left half
        if arr[mid] < x:
            low = mid + 1
 
        # If x is smaller, ignore right half
        elif arr[mid] > x:
            high = mid - 1
 
        # means x is present at mid
        else:
            return mid
 
    # If we reach here, then the element was not present
    return -1
 
 
# Test array
arr = [ 2, 3, 4, 10, 40 ]
x = 10
 
# Function call
result = binary_search(arr, x)
 
if result != -1:
    print("Element is present at index", str(result))
else:
    print("Element is not present in array")

Element is present at index 3


In [14]:
def insertionSort(arr): 
  
    # Traverse through 1 to len(arr) 
    for i in range(1, len(arr)): 
  
        key = arr[i] 
  
        # Move elements of arr[0..i-1], that are 
        # greater than key, to one position ahead 
        # of their current position 
        j = i-1
        while j >=0 and key < arr[j] : 
                arr[j+1] = arr[j] 
                j -= 1
        arr[j+1] = key 
  
  
# Driver code to test above 
arr = [12, 11, 13, 5, 6] 
insertionSort(arr) 
print ("Sorted array is:") 
for i in range(len(arr)): 
    print ("%d" %arr[i]) 

Sorted array is:
5
6
11
12
13


In [15]:
# Python program for implementation of Quicksort Sort 
  
# This function takes last element as pivot, places 
# the pivot element at its correct position in sorted 
# array, and places all smaller (smaller than pivot) 
# to left of pivot and all greater elements to right 
# of pivot 
  
  
def partition(arr, low, high): 
    i = (low-1)         # index of smaller element 
    pivot = arr[high]     # pivot 
  
    for j in range(low, high): 
  
        # If current element is smaller than or 
        # equal to pivot 
        if arr[j] <= pivot: 
  
            # increment index of smaller element 
            i = i+1
            arr[i], arr[j] = arr[j], arr[i] 
  
    arr[i+1], arr[high] = arr[high], arr[i+1] 
    return (i+1) 
  
# The main function that implements QuickSort 
# arr[] --> Array to be sorted, 
# low  --> Starting index, 
# high  --> Ending index 
  
# Function to do Quick sort 
  
  
def quickSort(arr, low, high): 
    if len(arr) == 1: 
        return arr 
    if low < high: 
  
        # pi is partitioning index, arr[p] is now 
        # at right place 
        pi = partition(arr, low, high) 
  
        # Separately sort elements before 
        # partition and after partition 
        quickSort(arr, low, pi-1) 
        quickSort(arr, pi+1, high) 
  
  
# Driver code to test above 
arr = [10, 7, 8, 9, 1, 5] 
n = len(arr) 
quickSort(arr, 0, n-1) 
print("Sorted array is:") 
for i in range(n): 
    print("%d" % arr[i]),

Sorted array is:
1
5
7
8
9
10


In [18]:
def bubbleSort(ar):
   n = len(arr)
   # Traverse through all array elements
   for i in range(n):
   # Last i elements are already in correct position
      for j in range(0, n-i-1):
      # Swap if the element found is greater than the next element
        if ar[j] > ar[j+1] :
         ar[j], ar[j+1] = ar[j+1], ar[j]
# Driver code to test above
ar = ['t','u','t','o','r','i','a','l']
bubbleSort(ar)
print ("Sorted array is:")
for i in range(len(ar)):
   print (ar[i])

Sorted array is:
i
o
r
t
t
u
a
l
